[#9]: Configurable operators
joshcarr/react-structured-filter pull request #10
Opened 2017-01-29 21:23 UTC by nickdeis

For ticket #9 , a very naive implementation, but it should work given that react-structured filter is more about generating a tree and not actually implementing the filter.

2017-01-30 20:07 UTC, joshcarr requested changes
Can you address the eslint complaints? Run `npm run lint` to see the output.

2017-01-31 06:40 UTC, nickdeis commented
Sure thing.

2017-01-31 21:15 UTC, joshcarr commented on src/tokenizer/index.js
> +import objectAssign from "object-assign";
You are importing this, but I don't see it in `package.json`. Any reason why?

2017-02-01 05:41 UTC, nickdeis commented on src/tokenizer/index.js
> +import objectAssign from "object-assign";
It's a dependency for React. But maybe it should be added? It's better to be declarative.

2017-02-01 22:40 UTC, joshcarr commented on src/tokenizer/index.js
> +import objectAssign from "object-assign";
Yes please do explicitly add it to `package.json`

2017-02-03 02:38 UTC, nickdeis commented on package.json
> +    "object-assign":"^3.0.0"
This is the version used by react-datetime

2017-02-03 02:39 UTC, nickdeis commented
Updated package.json

2017-07-17 17:46 UTC, merged

2017-07-17 17:52 UTC, joshcarr commented
Released in [v4.4.0](https://github.com/joshcarr/react-structured-filter/releases/tag/v4.4.0)